### PR TITLE
3.4.0 Fixed:    FullAuto mode corrected,

### PR DESCRIPTION
**Pull request by it-praktyk**
```
  Fixed:    Small corrections of code based on PSScriptAnalyzer 1.6.0 sugestions
  Added:    Console window title will be set back after a demo end
  Added:    Own custom prompt can be used under demo
  Added:    SkipAddTheEndLine switch to don't display 'The end' line
  Added:    SkipAddDemoTime switch to don't display start/end demo and demo duration in
            a PowerShell console window
  Added:    backgroundColor parameter added - now PowerShell console don't need to be black
```

### CODE REVIEW

**Comment by it-praktyk** [comment]
I've created that pull request to your repository due that if you use Google to search Start-Demo.ps1 your repository is on the top of results.

My original contribution to PowerShell Code Repository you can find here: [Start-Demo.ps1 3.4.0](http://poshcode.org/6397).

**Comment by it-praktyk** [comment]
Updated contribution to PowerShell Code Repository: [Start-Demo.ps1 3.4.1](http://poshcode.org/6398)

**Comment by it-praktyk** [comment]
Updated contribution to PowerShell Code Repository: [Start-Demo.ps1 3.5.0](http://poshcode.org/6399)

**Comment by it-praktyk** [comment]
@dfinke , @TravisEz13, @adamdriscoll , @saveenr , @edhaack I hope that you will like that updates also :-)

**Comment by dahlbyk** [comment]
> I've created that pull request to your repository due that if you use Google to search Start-Demo.ps1 your repository is on the top of results.

Very thoughtful of you! I've taken the liberty of editing your comment links to reference `Start-Demo.ps1` in an effort to funnel some SEO love toward [PoshCode](http://poshcode.org/). I also added the URL for v3.5.0 to the file header (001973583192152804ff60d36fe073a9f5340670) as an additional signal.

Until Google figures out the correct canonical link for this script, I'll gladly merge any future updates you wish to include in this repo.

**Pull request merged**
